# -*- coding: utf-8 -*-
"""Taxonomy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DN0jfT6pS-SC5wXvHfzCb1hIaVVQI6q0

<a href="https://colab.research.google.com/github/Igor-source/Made_code/blob/main/Taxonomy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

!pip install biopython

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

filtered_df = pd.read_csv('/content/ListOforganisms.csv')
filtered_df

clean_bact = filtered_df['target_organism'].drop_duplicates().tolist()
display(len(clean_bact))
clean_bact

clean_bact = pd.DataFrame(clean_bact, columns=['target_organism'])
clean_bact

# filtered_df=filtered_df['type']
# filtered_df

# # Список элементов для удаления
# elements_to_remove = [
#     "Streptococcus sp. 'group B'",
#     "Streptococcus sp. 'group A'",
#     "Salmonella enterica subsp. enterica serovar Typhimurium",'Streptococcus pneumoniae R6',
#  'Streptococcus pneumoniae serotype 4 (strain ATCC BAA-334 / TIGR4)', 'Salmonella enterica subsp. enterica serovar Westhampton', 'Severe acute respiratory syndrome coronavirus 2','Salmonella enterica subsp. enterica serovar Paratyphi A','Salmonella enterica subsp. enterica serovar Abony', 'Salmonella enterica subsp. enterica serovar Typhi',
#  'Salmonella enterica subsp. enterica serovar Enteritidis'
# ]

# # Удаляем элементы
# my_list = [item for item in clean_bact if item not in elements_to_remove]

# # Результат
# my_list

import time
ID_list = []
from Bio import Entrez
Entrez.email = "iroslov.01@gmail.com"     # Always tell NCBI who you are
for bact in clean_bact['target_organism']:
    handle = Entrez.esearch(db="Taxonomy", term=bact)
    record = Entrez.read(handle)
    ID_list.append(record)
    time.sleep(3)  # add a 1-second delay between each request
    print(record)
print(ID_list)

# df =pd.DataFrame(ID_list)
# df['name'] = first_10_bacteria
# df

# df.to_csv('/content/drive/MyDrive/Susan_project/taxonomy_descriptor.csv', index=False)

df = pd.read_csv('/content/drive/MyDrive/Susan_project/taxonomy_descriptor.csv')
df

# df.to_excel('/content/drive/MyDrive/Susan_project/taxonomy_descriptor.xlsx')

df.dropna(subset=['TranslationStack'], inplace=True)
df

dff = df[['IdList', 'name']]
# dff.iloc[[10]]
# dfr = dff.drop(dff.index[10]) # removing 10th row
dfr = dff.reset_index(drop=True)

# dfr = dfr.drop([463,327,277])
# dfr.reset_index(drop=True, inplace=True)
dfr

# Функция для удаления всего после второго слова
def clean_bacteria_name(name):
    # Разделяем строку по пробелам и берем только первые два слова
    return ' '.join(name.split()[:2])

# Применяем функцию к столбцу с названиями бактерий
dfr['name'] = dfr['name'].apply(clean_bacteria_name)

# Выводим результат
dfr

import ast

def convert_to_list(x):
    if isinstance(x, str):
        x = x.strip().strip("'\"")  # Удаляем лишние пробелы и внешние кавычки
        try:
            x = ast.literal_eval(x)
        except Exception as e:
            print(f"Ошибка при преобразовании в список на значении {x}: {e}")
            x = np.nan
    return x

dfr['IdList'] = dfr['IdList'].apply(convert_to_list)

print(dfr['IdList'].apply(type).value_counts())

def remove_first_value(x):
    if isinstance(x, (list, ListElement)):
        if len(x) > 1:
            return x[1]  # Возвращаем второй элемент списка
        elif len(x) == 1:
            return x[0]  # Если только один элемент, возвращаем его
        else:
            return np.nan
    else:
        return x  # Возвращаем значение как есть, если оно не список

import time
from Bio import Entrez
from Bio.Entrez.Parser import ListElement
Entrez.email = "iroslov.01@gmail.com"

dfr['IdList'] = dfr['IdList'].apply(remove_first_value)

print(dfr[['IdList', 'name']].head(10))

def get_tax_id(bacterial_name):
    """Fetches the Taxonomy ID for a given bacterial name."""
    try:
        search_handle = Entrez.esearch(db="taxonomy", term=bacterial_name)
        search_results = Entrez.read(search_handle)
        search_handle.close()

        # Get the first Taxonomy ID from the search results
        if search_results["IdList"]:
            return search_results["IdList"][0]
        else:
            print(f"No Taxonomy ID found for {bacterial_name}")
            return None
    except Exception as e:
        print(f"Error searching for {bacterial_name}: {e}")
        return None

def get_superkingdom_from_name(bacterial_name):
    """Fetches the superkingdom for a given bacterial name."""
    tax_id = get_tax_id(bacterial_name)
    if tax_id:
        try:
            handle = Entrez.efetch(db="taxonomy", id=tax_id, retmode="xml")
            record = Entrez.read(handle)
            handle.close()

            if record:
                for lineage in record[0]['LineageEx']:
                    if lineage['Rank'] == 'superkingdom':
                        return lineage['ScientificName']
            return None
        except Exception as e:
            print(f"Error fetching superkingdom for Taxonomy ID {tax_id}: {e}")
            return None
    return None

# Create a new column 'Superkingdom' in dfr
dfr['Superkingdom'] = None

# Iterate through the rows and fetch the superkingdom for each bacterial name in the 'name' column
for index, row in dfr.iterrows():
    bacterial_name = row['name']

    # Fetch the superkingdom and add delay
    superkingdom = get_superkingdom_from_name(bacterial_name)
    dfr.at[index, 'Superkingdom'] = superkingdom
    time.sleep(0.4)  # Delay to comply with NCBI rate limits

dfr

dfr.to_csv("/content/drive/MyDrive/Susan_project/taxonomy_kingdom.csv", index=False)
dfr.to_excel("/content/drive/MyDrive/Susan_project/taxonomy_kingdom.xlsx", index=False)

# Создаем пустой список для хранения уровня таксономической классификации "Kingdom"
kingdom = []

# Создаем пустые DataFrame для бактерий и грибов
bacteria_df = pd.DataFrame()
fungi_df = pd.DataFrame()

# Итерация по DataFrame
for i in range(len(dfr)):
    id_value = dfr['IdList'].iloc[i]

    # Проверяем, является ли ID допустимым
    if pd.isna(id_value) or not isinstance(id_value, (str, int)):
        print(f"Некорректный ID на индексе {i}: {id_value}")
        kingdom.append(np.nan)
        continue

    id_value = str(id_value)  # Преобразуем ID в строку

    try:
        handle = Entrez.efetch(db="Taxonomy", id=id_value, retmode="xml")
        records = Entrez.read(handle)
        handle.close()

        # Получаем таксономическую линию
        tax = records[0]["Lineage"].split("; ")
        time.sleep(0.2)

        # Проверяем, являются ли это грибами или бактериями
        if any("Fungi" in tax_elem for tax_elem in tax):
            # Добавляем уровень "Kingdom" в список
            kingdom.append(tax[3] if len(tax) > 3 else np.nan)
            # Добавляем данные в DataFrame грибов
            fungi_df = pd.concat([fungi_df, dfr.iloc[[i]]], ignore_index=True)
        elif any("Bacteria" in tax_elem for tax_elem in tax):
            # Добавляем уровень "Kingdom" в список
            kingdom.append(tax[1] if len(tax) > 1 else np.nan)
            # Добавляем данные в DataFrame бактерий
            bacteria_df = pd.concat([bacteria_df, dfr.iloc[[i]]], ignore_index=True)
        else:
            kingdom.append(np.nan)
    except Exception as e:
        print(f"Ошибка при обработке ID {id_value} на индексе {i}: {e}")
        kingdom.append(np.nan)

# Создаем новый столбец в DataFrame для уровня классификации "Kingdom"
dfr["Kingdom"] = kingdom

# Сохраняем модифицированный DataFrame в новый файл
dfr.to_csv("taxonomy_kingdom.csv", index=False)

# Выводим столбец Kingdom
print(dfr["Kingdom"])

# # Функция для удаления первого значения из списков в столбце 'IdList'
# def remove_first_value(x):
#     if isinstance(x, (list, ListElement)):
#         if len(x) > 1:
#             return x[1]  # Возвращаем второй элемент списка
#         elif len(x) == 1:
#             return x[0]  # Если только один элемент, возвращаем его
#         else:
#             return np.nan
#     else:
#         return x  # Возвращаем значение как есть, если оно не список

# import time
# from Bio import Entrez
# from Bio.Entrez.Parser import ListElement
# Entrez.email = "iroslov.01@gmail.com"

# dfr['IdList'] = dfr['IdList'].apply(lambda x: x if isinstance(x, str) else str(x))

# # Применяем функцию к столбцу 'IdList'
# dfr['IdList'] = remove_first_value(dfr['IdList'])
# dfr

# print(dfr['IdList'].apply(type).value_counts())

# Создаем пустой список для хранения уровня таксономической классификации "Kingdom"
kingdom = []

# Создаем пустые DataFrame для бактерий и грибов
bacteria_df = pd.DataFrame()
fungi_df = pd.DataFrame()

# Итерация по DataFrame
for i in range(len(dfr)):
    id_value = dfr['IdList'].iloc[i]

    # Проверяем, является ли ID допустимым
    if pd.isna(id_value) or not isinstance(id_value, (str, int)):
        print(f"Некорректный ID на индексе {i}: {id_value}")
        kingdom.append(np.nan)
        continue

    id_value = str(id_value)  # Преобразуем ID в строку

    try:
        handle = Entrez.efetch(db="Taxonomy", id=id_value, retmode="xml")
        records = Entrez.read(handle)
        handle.close()

        # Получаем таксономическую линию
        tax = records[0]["Lineage"].split("; ")
        time.sleep(0.2)

        # Проверяем, являются ли это грибами или бактериями
        if any("Fungi" in tax_elem for tax_elem in tax):
            # Добавляем уровень "Kingdom" в список
            kingdom.append(tax[3] if len(tax) > 3 else np.nan)
            # Добавляем данные в DataFrame грибов
            fungi_df = pd.concat([fungi_df, dfr.iloc[[i]]], ignore_index=True)
        elif any("Bacteria" in tax_elem for tax_elem in tax):
            # Добавляем уровень "Kingdom" в список
            kingdom.append(tax[1] if len(tax) > 1 else np.nan)
            # Добавляем данные в DataFrame бактерий
            bacteria_df = pd.concat([bacteria_df, dfr.iloc[[i]]], ignore_index=True)
        else:
            kingdom.append(np.nan)
    except Exception as e:
        print(f"Ошибка при обработке ID {id_value} на индексе {i}: {e}")
        kingdom.append(np.nan)

# Создаем новый столбец в DataFrame для уровня классификации "Kingdom"
dfr["Kingdom"] = kingdom

# Сохраняем модифицированный DataFrame в новый файл
dfr.to_csv("taxonomy_kingdom.csv", index=False)

# Выводим столбец Kingdom
print(dfr["Kingdom"])

"""##List convert to str"""

# dfr['IdList'] = dfr['IdList'].apply(lambda x: x if isinstance(x, str) else str(x))
# # dfr = dfr.drop([4,8])
# dfr

# dfr.reset_index(drop=True, inplace=True)
# dfr

# # Создаем пустые списки для хранения каждого уровня таксономической классификации
# superkingdom = []
# clade = []
# kingdom = []
# phylum = []
# class_ = []
# order = []
# family = []
# genus = []
# species = []

# # Создаем пустые DataFrame для бактерий и грибов
# bacteria_df = pd.DataFrame()
# fungi_df = pd.DataFrame()

# # Итерация по DataFrame
# for i in range(len(dfr)):
#     id_value = dfr['IdList'][i]

#     # Проверяем, является ли ID допустимым
#     if pd.isna(id_value) or not isinstance(id_value, str):
#         print(f"Некорректный ID на индексе {i}: {id_value}")
#         # Добавляем np.nan для каждого уровня классификации
#         superkingdom.append(np.nan)
#         kingdom.append(np.nan)
#         clade.append(np.nan)
#         phylum.append(np.nan)
#         class_.append(np.nan)
#         order.append(np.nan)
#         family.append(np.nan)
#         genus.append(np.nan)
#         species.append(np.nan)
#         continue

#     try:
#         handle = Entrez.efetch(db="Taxonomy", id=id_value, retmode="xml")
#         records = Entrez.read(handle)

#         # Получаем таксономическую линию
#         tax = records[0]["Lineage"].split("; ")
#         time.sleep(0.2)

#         # Проверяем, являются ли это грибами или бактериями
#         if "Fungi" in tax:
#             # Извлекаем каждый уровень классификации и добавляем в соответствующий список
#             superkingdom.append(tax[1] if len(tax) > 1 else np.nan)
#             kingdom.append(tax[3] if len(tax) > 3 else np.nan)
#             clade.append(tax[2] if len(tax) > 2 else np.nan)
#             phylum.append(tax[4] if len(tax) > 4 else np.nan)
#             class_.append(tax[5] if len(tax) > 5 else np.nan)
#             order.append(tax[6] if len(tax) > 6 else np.nan)
#             family.append(tax[7] if len(tax) > 7 else np.nan)
#             genus.append(tax[8] if len(tax) > 8 else np.nan)
#             species.append(tax[-1] if len(tax) > 0 else np.nan)
#             # Добавляем данные в DataFrame грибов
#             fungi_df = pd.concat([fungi_df, dfr.iloc[[i]]], ignore_index=True)

#         elif "Bacteria" in tax:
#             # Извлекаем каждый уровень классификации и добавляем в соответствующий список
#             kingdom.append(tax[1] if len(tax) > 1 else np.nan)
#             if "group" in tax[2]:
#                 clade.append(tax[2] if len(tax) > 2 else np.nan)
#                 phylum.append(tax[3] if len(tax) > 3 else np.nan)
#                 class_.append(tax[4] if len(tax) > 4 else np.nan)
#                 order.append(tax[5] if len(tax) > 5 else np.nan)
#                 family.append(tax[6] if len(tax) > 6 else np.nan)
#                 genus.append(tax[7] if len(tax) > 7 else np.nan)
#                 species.append(tax[-1] if len(tax) > 0 else np.nan)
#             else:
#                 clade.append(np.nan)
#                 phylum.append(tax[2] if len(tax) > 2 else np.nan)
#                 class_.append(tax[3] if len(tax) > 3 else np.nan)
#                 order.append(tax[4] if len(tax) > 4 else np.nan)
#                 family.append(tax[5] if len(tax) > 5 else np.nan)
#                 genus.append(tax[6] if len(tax) > 6 else np.nan)
#                 species.append(tax[-1] if len(tax) > 0 else np.nan)
#             # Добавляем данные в DataFrame бактерий
#             bacteria_df = pd.concat([bacteria_df, dfr.iloc[[i]]], ignore_index=True)

#     except Exception as e:
#         print(f"Ошибка при обработке ID {id_value} на индексе {i}: {e}")
#         # Добавляем np.nan для каждого уровня классификации
#         superkingdom.append(np.nan)
#         kingdom.append(np.nan)
#         clade.append(np.nan)
#         phylum.append(np.nan)
#         class_.append(np.nan)
#         order.append(np.nan)
#         family.append(np.nan)
#         genus.append(np.nan)
#         species.append(np.nan)

# # Создаем новые столбцы в DataFrame для каждого уровня классификации
# dfr["Kingdom"] = kingdom
# dfr["clade"] = clade
# dfr["Phylum"] = phylum
# dfr["Class"] = class_
# dfr["Order"] = order
# dfr["Family"] = family
# dfr["Genus"] = genus
# dfr["Species"] = species

# # Сохраняем модифицированный DataFrame в новый файл
# dfr.to_csv("taxonomy_descriptor.csv", index=False)


# print(Kingdom)

dfr
#The information is not true so the information is obtained again

import pandas as pd

# Список единиц измерения
concentration_units = [
    'uM', 'mm', 'mg/dL', 'mg/L', 'IU/L', 'g', 'u/L', 'hr', 'CELLS/uL', 'g/dL',
    'meq/L', 'G/DL', 'MEQ/L', 'mg kg-1', 's', 'ug/L', 'mM', 'umol/L', '/s',
    'mg/ml', 'x10E3/uL', 'nM', 'pg', 'fL', 'x10_2/uL', 'x10_4/uL', 'x10_4/ul',
    '10\'-2 umol/ml', 'umol/ml', 'PG', 'FL', 'x10E6/uL', 'MMOL/L', 'mg l-1',
    '/100WBC', 'cm', '/uM/s', '/s/microM', '/hr', 'um', 'ng/ml', 'M',
    'log10CFU/ml', 'mm2', 'mg ml-1', '/ml', 'log10CFU', 'ug', 'uM/ml',
    '10\'-2microM', '/mM/s', 'min', 'microM', 'millimeter', 'uM/L', 'day',
    'mm3', 'mmHg', 'microg/ml', '10\'8/ml', 'uM l-1', 'mg.hr/L', 'ug mg-1',
    '10\'-2micromol/ml', 'mmol/L', 'nm', 'ml/min.kg', '10\'5/ml', '10\'6/M/s',
    'U', 'microg.hr/mL', '10\'5/M/s', 'mg Kg-1', '10\'-3micromol/ml', 'log10CFU/ml.hr',
    'mg/kg/day', 'ug.hr/ml', 'nmol/ml.min', 'g ml-1', 'deltalog10CFU',
    '/M/s', 'mg mouse-1', '10\'3CFU/ml', 'mmol/ml', '10^4/ml', 'nmol/ml',
    'uL/ml', 'CFU', 'U/min', '10\'-2umol', 'log10CFU/g', '10^3/ml', 'umol',
    'ng', '10^8/ml', 'U/L', '10\'4/M/s', '10^9/ml', '10\'-2mmol/ml',
    'ug/uL', 'L/Kg', 'g/ml', 'ug hr ml-1', 'nmol/min/mg', 'Kg', 'mg',
    '10^2/ml', 'ppm', 'deltalog10CFU/ml', 'a.u.', 'ml min-1 kg-1', '10^7/ml',
    '10^5/ml', '10^6/ml', 'pmol', 'hr.microg/ml', 'ml', 'pg/ml', 'uL/hr/cm2',
    'mm/mg', 'CFU/ml', '10\'-3microM', 'M min-1 (M of enzyme)-1', '10\'7/M/s',
    'nmol', 'ug/ml.hr', 'microg', 'ml/g', 'ug kg-1', 'ng ml-1', 'microg/cm3',
    'ug ml-1 ml-1', 'uM/hr', '10\'-3 log10CFU/ml/hr', 'ug mL-1', 'nmol/L',
    'nmol/min', 'ml/kg', '10^-3mM', 'ug/ml/hr', '10\'-3uM/ml', 'mg kg-1 day-1',
    'ng g-1', 'ml/hr.kg', 'l kg-1', '10\'3/M/s', '10\'-7No_unit', 'uM min-1mg-1',
    '10e4 M-1 s-1', 'U/ml', 'ug min ml-1', 'M l-1', '10\'-3 ug/ml', 'L/hr/kg',
    'microL/min/mg', 'mg.min/L', '10\'-6 ug/ml', '10\'-8M', '10\'3/M',
    'deltalog10CFU/ml.hr', '10\'-7cm2/sec', 'log10RLU', '10^7/g', 'cpm/min',
    'pmol/min', '10\'-6M', 'Ratio', 'microg.min/mL', '10^-8M', '10^-9No_unit',
    'uM kg-1', 'mmHg/min', 'um/s', 'nmol/sec', '10^-1/s', '10\'2/M/s',
    '10^-6/s', '10^1/Ms', '(g kidney)-1', 'ng hr ml-1', 'microg/min/ml',
    '10\'6/ml', '%ID', 'N', '10^-1M', '10^8/g', '10\'6/s/M', '10\'10CFU',
    'ug/L/h', 'hr.ng/ml', 'ng.hr/ml', 'g/dl', 'log CFU', '10\'-5 ug/ml',
    'umol/min/mg', 'ug/sq.cm', '10\'7/g', 'nm/s', '10\'9/L', '10\'9/g',
    's-1', '10\'8CFU/ml', '1/Ms', 'ucm/s', '10\'2 ug/ml', '10\'-6cm2/s',
    '10\'-2 ug/ml', 'microg/cm2', '10\'-1/hr', 'uM min-1', 'umol/Kg',
    'ug min-1 ml-1', '10\'4CFU/ml', 'RLU', '10\'3L/mol', 'l', '10\'7/ml',
    '10\'2/ml', '10\'3/ml', 'ml/min.Kg', '10\'2 uM/s', '10\'5/s/M',
    '10\'6CFU/ml', '10\'7CFU/ml', '10\'2/g', 'cm s-1', 'M-1', '10^-5No_unit',
    '10^6cm/s', '1/M*s', '1/M', '10\'9CFU', 'se-1', '/uL', '10\'8CFU',
    '10\'5CFU', 'g/L', 'L/kg', 'mmol/min/mg', 'ml hr-1 kg-1', 'ml kg-1',
    '10\'12/L', 'ug/g', 'uM.hr/ml', '10\'7CFU', '10\'-6 mol/L', '10^7CFU',
    '10^7CFU/g', '10^2/Ms', 'mg kg-1 p.o.', '1/S', 'weeks', '10\'-4 ug/ml',
    'mg/kg', 'ug ml-1 hr-1', '10\'-7 ug/ml', 'ug.hr/L'
]

# Функция для перевода величин в стандартный вид [ug.mL-1]
def convert_to_ug_mL(concentration):
    conversion_factors = {
        'uM': 1e-6,
        'mm': 1e-3,
        'mg/dL': 1e-3,
        'mg/L': 1e-6,
        'IU/L': 1e-6,
        'g': 1e-6,
        'u/L': 1e-6,
        'CELLS/uL': 1e-6,
        'g/dL': 1e-6,
        'meq/L': 1e-6,
        'ug/L': 1e-6,
        'mM': 1e-3,
        'umol/L': 1e-6,
        'nM': 1e-9,
        'pg': 1e-12,
        'mg/ml': 1e-3,
        'ug': 1e-6,
        'uM/ml': 1e-6,
        'mmol/L': 1e-3,
        'mg/kg': 1e-3,
        'microM': 1e-6,
        'nmol': 1e-9,
        'mg': 1e-3,
        'g/ml': 1e-3,
        'ug/mL': 1e-6,
    }

    if concentration in conversion_factors:
        # Конвертируем в ug.mL-1
        return 1 / conversion_factors[concentration]  # возвращаем коэффициент, чтобы выразить в ug.mL-1
    return None

# Конвертация всех величин в ug.mL-1
standard_values = {unit: convert_to_ug_mL(unit) for unit in concentration_units}
standard_values = {k: v for k, v in standard_values.items() if v is not None}

# Фильтрация неконцентрированных величин
non_concentration_units = [
    'hr', 's', '/s', 'cm', '/100WBC', 'day', 'fl', 'min', 'g', 'mL',
    'uL/hr/cm2', 'CFU', 'U/min', 'log10CFU', 'pg/ml', 'uL/ml', 'ml',
    'g/dL', 'log10CFU/g', '10\'-5 ug/ml', 'weeks'
]

# Вывод результатов
print("Концентрации в ug.mL-1:")
for original, standard in standard_values.items():
    print(f"{original}: {standard:.2f} ug.mL-1")

print("\nНеконцентрированные величины:")
for non_concentration in non_concentration_units:
    print(non_concentration)

